### ISSUE TITLE
[Discussion] Split create-tar.sh 

### ISSUE THREAD

**Issue by msirringhaus** [openSUSE/firefox-scripts#4]
Currently, we copy the whole of `create-tar.sh` into OBS. 
So there is the chance that changes to one `create-tar.sh` do not get merged to other OBS branches, having several similar but different scripts hanging around (which is the state I started from). 

In principle, this github repo here should prevent this. 
But there are two problems I see:
1. Keeping this repo conflict free will probably be a bit challenging, if we only copy the final `create-tar.sh` into it from whatever FF or TB version we just built. The main content stays the same, but RELEASE_TAG, VERSION and so on change, which will probably lead to some merge conflicts. 
This is not too bad, but would cause some workflow-friction nonetheless. 
2. There are 2 additional step right now: copying `create-tar.sh` to your build-dir, and after editing and running, copy it back to this repo. This final step can easily be forgotten and thus possible changes lost, or at least made branches inconsistent.

To prevent this, I propose to split off the first few lines from create-tar.sh, so basically contain only the "source stamp info". Lets call it something like `tar_stamps`, which would look like:
```
$ cat tar_stamps
PRODUCT="firefox"
CHANNEL="esr68"
FF_RELEASE_TAG=""
PREV_VERSION="68.0"
PREV_VERSION_SUFFIX="b11"
VERSION="68.0"
VERSION_SUFFIX="b14"
```

The rest of `create-tar.sh` would simply go into your `$PATH` and get this stamp-file as a commandline argument, source it, and start working.

`firefox-scripts` would not get these stamp-files, but `firefox-maintenance` and OBS would (but would not get `create-tar.sh`)

With that approach accidental "lost/unmerged changes" to `create-tar.sh` will get very unlikely, as it will not be copied anymore at all, but lives in the repo, which should be part of your `$PATH`.

For a new version, you only copy the `tar_stamps` from the last version and adapt those 7 lines.

Comments?

**Comment by cgrobertson** [comment]
This sounds like a reasonable solution. One tar_stamps file for MozillaFirefox project and one for MozillaThunderbird projects. Makes sense. Then we don't have conflicts with different create-tar.sh's.

**Comment by cgrobertson** [comment]
One request: Document create-tar.sh usage and add a --help option to print out the usage. (Include usage of the tar_stamps file.)

**Comment by msirringhaus** [comment]
I did not add a `--help` directly, to keep the script simple. To print out the help-text, simply call `create-tar.sh` with no arguments (or a non-existent file. `--help` probably qualifies as a non-existent file as well)
