### ISSUE TITLE
fetch correct mozilla base for Thunderbird in create-tar.sh automatically

### ISSUE THREAD

**Issue by wrosenauer** [openSUSE/firefox-scripts#6]
Seems that nowadays the correct mozilla branch and revision for a TB release is encoded in the file .gecko_rev.yml within the comm repository. We could possibly use this.

**Comment by msirringhaus** [comment]
There is also `source-stamp.txt`, but that seems to be broken. It points to an Mozilla-internal URL with a revision encoded in it, pointing to `/mozilla-unified/rev/...`. If going to the publicly available `hg.mozilla.org//mozilla-unified/rev/...` however results in an error.

**Comment by wrosenauer** [comment]
Which source-stamp.txt you mean?
The current comm-esr68 candidate (68.1.1) has
https://hg.mozilla.org/releases/comm-esr68/file/41c0a3653f95cf6158a2b49ab7cb19327c50e9e8/.gecko_rev.yml
I guess we can ignore the GECKO_BASE_REPOSITORY.
In any case I filed this as a possible enhancement request to not forget it.

**Comment by msirringhaus** [comment]
Sorry, I meant `sourcestamp.txt`, which is in the thunderbird-tarball (provided by Mozilla) in the top level. The revision encoded in this URL is the same as `GECKO_HEAD_REV` in `.gecko_rev.yml`(although the link does not work itself)
